spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: Mythh1711@

jpa:
  hibernate:
    ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

